name: Build and Deploy 
run-name: Build and Deploy 
on:
  workflow_dispatch
jobs:
  deploy-to-s3:
    name: Deploy To S3
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
      - name: Build
        run: |
          npm ci
          npm build 
        shell: bash
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: /dist

