name: Build and Deploy 
run-name: Build and Deploy 
on:
  workflow_dispatch
jobs:
  deploy-to-s3:
    name: Deploy To S3
    runs-on: 'ubuntu-latest'
    steps:
      - name: Test steps
        run: |
          echo "Sagar"
        shell: bash

